
	</div>
<hr class="imInvisible" />
<a name="imGoToCont"></a>
	<div id="imContent">

<!-- Page START -->
<div id="imPage">

<div id="imCel7_00">
<div id="imCel7_00_Cont">
	<div id="imObj7_00">
<!-- Debut Barner -->
<p>
Les modifications de Franklin peuvent commencer ici
</p>

<div align="left">
<table bgcolor="#b0c4de"  width=98% border="1" cellpadding="0" cellspacing="0" summary="">
<td> Franklin </td>
<td>
 <form action="tobedefined.php" method="post">
 Recherche rapide <input type="Text" name="recherche">
 Lieu <input type="Text" name="lieu">
 <!--Rubrique <input type="Text" name="rubrique"-->
 Rubrique <select  name="Rubrique">
  <option value="01" selected>Toutes les  Rubriques </option>
  <option value="02">Immobilier</option>
  <option value="03">Electromenager</option>
  <option value="04">Automobile</option>
  <option value="05">Electronique</option>
  <option value="06">Produits agricoles</option>
  <option value="07">Machines agricoles</option>
  <option value="08">Objets d'art'</option>
  <option value="09">Tableaux</option>
  <option value="10">Jobs et Business</option>
  <option value="11">Services</option>
  </select>
 <input type="submit" value="Lancer recherche">
 </form>
 </td>
</table>
</div>
<div>
<table width=98% border="1" cellpadding="0" cellspacing="0" summary="">
<td align="left" valign="top"> <marquee direction="right">Bienvenu sur votre site d'insertion gratuite </marquee></td>
<td align="right" valign="top"><marquee>Publicite 2</marquee></td>
</table>

</div>
<!-- Fin Barner -->

