

</p>

<div>
<table width=98% border="1" cellpadding="0" cellspacing="0" summary="">
<td align="left" valign="top"> <marquee direction="right">Bienvenue sur votre site d'insertion gratuite </marquee></td>
<td align="right" valign="top"><marquee>Des sms gratuits tr&eacute;s prochainement sur ce site</marquee></td>
</table>

</div>
<!-- Fin Barner -->

<!--debut corps-->

<!-- Debut Corps -->
<div align="left" >

<table align="left" width=98% border="1" cellpadding="1" cellspacing="1" summary="">
    <tr>
        <!-- Barre de navi gauche-->
        <td valign="top" width="150">
