
<div id="imBody">
	<div id="imMenuMain">

<!-- Menu START -->
<a name="imGoToMenu"></a><p class="imInvisible">Menu principal:</p>
<div id="imMnMn">
<ul>
	<li><a class="imMnItm_1" href="index.html" title=""><span class="imHidden">Accueil</span></a></li>
	<li><a class="imMnItm_2" href="les_annonces.html" title=""><span class="imHidden">Les annonces</span></a></li>
	<li><a class="imMnItm_3" href="insertion.html" title=""><span class="imHidden">Insertion</span></a></li>
	<li><a class="imMnItm_4" href="mon_shop.html" title=""><span class="imHidden">Mon Shop</span></a></li>
	<li><a class="imMnItm_5" href="aide.html" title=""><span class="imHidden">Aide</span></a></li>
</ul>
</div>
<!-- Menu END -->

	

