<!-- navi de droite -->
        <td align="left" valign="top" width="150">
        ici vient les renseignements, les publicitees et les indications
        <table width=100% border="1" cellpadding="1" cellspacing="1" summary="">
    <tr>
        <!--td><img src="images\cameroon-map.jpg" width="75" height="74" border="0" alt="Carte du Cameroun"-->
        <td><img src="images/cameroon-map.jpg"  width="150" height="200" border="0" alt="Carte du Cameroun">
        </td>
    </tr>
    <!--
    <tr>
        <td>pp</td>
    </tr>
    <tr>
        <td>pp</td>
    </tr>
    <tr>
        <td>pp</td>
    </tr>
   -->
</table>
        </td>
<!-- Fin navi de droite -->
